### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by mb-wali** [tu-graz-library/invenio-records-lom#14]
### checklist for v1.0.0

- [ ] lom json schema with mappings.
- [ ] update readthedocs documentation see #12 
- [ ] github ci publish to pypi see #13 
- [ ] model or no model #15 
- [ ] lom records permissions see #16 
- [ ] UI - templates see #17
